# Use an official Ubuntu base image
FROM ubuntu:20.04

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary dependencies including Jansson and libmagic libraries
RUN apt-get update && apt-get install -y \
    build-essential \
    automake \
    libtool \
    pkg-config \
    wget \
    unzip \
    python3 \
    python3-pip \
    python3-setuptools \
    libjansson-dev \
    libmagic-dev \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /opt

# Set entrypoint to allow compilation and export of binaries when running the container
ENTRYPOINT ["/bin/bash", "-c", "\
    if [ -d /source ]; then \
    echo 'Using YARA source from /source'; \
    cd /source && ./bootstrap.sh && ./configure --enable-cuckoo --enable-magic --enable-dotnet && make && make install && \
    mkdir -p /output && cp /usr/local/bin/yara /output/ && cp /usr/local/lib/libyara* /output/; \
    else \
    echo 'No source found in /source directory! Please mount a YARA source directory.'; \
    exit 1; \
    fi"]

# Set output directory as a volume
VOLUME /output
