# Use an official Ubuntu base image
FROM ubuntu:20.04

ARG YARA_VERSION

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary dependencies including Jansson library
RUN apt-get update && apt-get install -y \
    build-essential \
    automake \
    libtool \
    pkg-config \
    wget \
    unzip \
    python3 \
    python3-pip \
    python3-setuptools \
    libjansson-dev \  
    libmagic-dev \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /opt

# Copy the YARA source zip file to the container
ARG YARA_VERSION
COPY yara-${YARA_VERSION}.zip /opt/

# Unzip the YARA source code
ARG YARA_VERSION
RUN unzip yara-${YARA_VERSION}.zip && \
    rm yara-${YARA_VERSION}.zip

# Navigate to the YARA source directory
ARG YARA_VERSION
WORKDIR /opt/yara-${YARA_VERSION}

# Compile and install YARA
RUN ./bootstrap.sh && \
    ./configure --enable-cuckoo --enable-magic --enable-dotnet && \
    make && \
    make install && \
    ldconfig

ENTRYPOINT [ "yara" ]